### ISSUE TITLE
Question: why is this not using React.lazy?

### ISSUE THREAD

**Issue by hswolff** [reactjs/react-gradual-upgrade-demo#2]
Hello!

I’ve read the README and it notes that this demo essentially re-creates the functionality of React.lazy but I can’t see any explanation as to why that is the case. 

So...why is it so?

**Comment by gaearon** [comment]
`React.lazy` wouldn't work because we want the actual rendering to be done by the *inner* React but the waiting needs to be done by the *outer* React. There's just no way to express that via the lazy API.
