### ISSUE TITLE
Gradual Updates with React 16

### ISSUE THREAD

**Issue by yurylavrukhin** [reactjs/react-gradual-upgrade-demo#3]
Here's the quote from the blog post https://reactjs.org/blog/2020/08/10/react-v17-rc.html

![image](https://user-images.githubusercontent.com/26966797/92547629-7ff8c680-f27f-11ea-8979-179439ca75c3.png)
> Thanks to this change, it is now safer to embed a React tree managed by one version inside a tree managed by a different React version. Note that for this to work, both of the versions would need to be 17 or higher, which is why upgrading to React 17 is important.

> **Note that for this to work, both of the versions would need to be 17 or higher**

But this repository uses React 16 inside React 17, could it possibly create bugs with events?

**Comment by gaearon** [comment]
Yes, this is correct — we’re using 16 and 17 here to demonstrate that different versions work side by side, but ideally you’d use this *in the future* (e.g. 17 and 18) where both versions are 17+.
